CREATE TABLE administrador(
    idAdmin INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    contra VARCHAR NOT NULL
)

ALTER TABLE administrador
ADD CONSTRAINT administrador_usuario_unique UNIQUE (usuario);